// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using click_collect;

#nullable disable

namespace projClickCollect.Migrations
{
    [DbContext(typeof(VendasContext))]
    [Migration("20260623042133_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("click_collect.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            IdCliente = 1,
                            Email = "alice.campos@email.com",
                            NomeCliente = "Alice Campos"
                        },
                        new
                        {
                            IdCliente = 2,
                            Email = "bruno.h@email.com.br",
                            NomeCliente = "Bruno Henrique"
                        },
                        new
                        {
                            IdCliente = 3,
                            Email = "camila.rocha@provedor.com",
                            NomeCliente = "Camila Rocha"
                        },
                        new
                        {
                            IdCliente = 4,
                            Email = "daniel.machado@email.com",
                            NomeCliente = "Daniel Machado"
                        },
                        new
                        {
                            IdCliente = 5,
                            Email = "eduarda.nunes@email.com.br",
                            NomeCliente = "Eduarda Nunes"
                        },
                        new
                        {
                            IdCliente = 6,
                            Email = "felipe.costa@email.com",
                            NomeCliente = "Felipe Costa"
                        },
                        new
                        {
                            IdCliente = 7,
                            Email = "gabi.pereira@provedor.com",
                            NomeCliente = "Gabriela Pereira"
                        },
                        new
                        {
                            IdCliente = 8,
                            Email = "hugo.martins@email.com.br",
                            NomeCliente = "Hugo Martins"
                        },
                        new
                        {
                            IdCliente = 9,
                            Email = "isa.ribeiro@email.com",
                            NomeCliente = "Isabela Ribeiro"
                        },
                        new
                        {
                            IdCliente = 10,
                            Email = "jv.mendes@email.com.br",
                            NomeCliente = "João Vitor Mendes"
                        },
                        new
                        {
                            IdCliente = 11,
                            Email = "karina.silva@provedor.com",
                            NomeCliente = "Karina Silva"
                        },
                        new
                        {
                            IdCliente = 12,
                            Email = "leo.santos@email.com",
                            NomeCliente = "Leonardo Santos"
                        },
                        new
                        {
                            IdCliente = 13,
                            Email = "marcelo.moraes@email.com.br",
                            NomeCliente = "Marcelo Moraes"
                        },
                        new
                        {
                            IdCliente = 14,
                            Email = "nat.gomes@email.com",
                            NomeCliente = "Natália Gomes"
                        },
                        new
                        {
                            IdCliente = 15,
                            Email = "otavio.castro@provedor.com",
                            NomeCliente = "Otávio Castro"
                        },
                        new
                        {
                            IdCliente = 16,
                            Email = "paula.azevedo@email.com.br",
                            NomeCliente = "Paula Azevedo"
                        },
                        new
                        {
                            IdCliente = 17,
                            Email = "ricardo.barros@email.com",
                            NomeCliente = "Ricardo Barros"
                        },
                        new
                        {
                            IdCliente = 18,
                            Email = "rafael.teixeira@email.com.br",
                            NomeCliente = "Rafael Teixeira"
                        },
                        new
                        {
                            IdCliente = 19,
                            Email = "sofia.monteiro@provedor.com",
                            NomeCliente = "Sofia Monteiro"
                        },
                        new
                        {
                            IdCliente = 20,
                            Email = "thiago.assis@email.com",
                            NomeCliente = "Thiago Assis"
                        });
                });

            modelBuilder.Entity("click_collect.Loja", b =>
                {
                    b.Property<int>("IdLoja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeLoja")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdLoja");

                    b.ToTable("Lojas");

                    b.HasData(
                        new
                        {
                            IdLoja = 1,
                            NomeLoja = "MC Donalds - Canoas, Centro",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 2,
                            NomeLoja = "Renner - Canoas, Mathias Velho",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 3,
                            NomeLoja = "NET - Canoas, Niterói",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 4,
                            NomeLoja = "Starbucks - Porto Alegre, Centro Histórico",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 5,
                            NomeLoja = "Royal Trudel - Porto Alegre, Menino Deus",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 6,
                            NomeLoja = "Mini-Kalzone - Porto Alegre, Sarandi",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 7,
                            NomeLoja = "Lauros - Gravataí, Centro",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 8,
                            NomeLoja = "Cremolatto - Gravataí, Castelo Branco",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 9,
                            NomeLoja = "Subway - Gravataí, Bernabé",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 10,
                            NomeLoja = "Nike - São Leopoldo, Feitoria",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 11,
                            NomeLoja = "Nike - São Leopoldo, Feitoria",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 12,
                            NomeLoja = "NewBalance - São Leopoldo, Vicentina",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 13,
                            NomeLoja = "São João - Novo Hamburgo, Canudos",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 14,
                            NomeLoja = "Panvel - Novo Hamburgo, Estância Velha",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 15,
                            NomeLoja = "Droga Raia - Novo Hamburgo, Boa Saúde",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 16,
                            NomeLoja = "Caça e Pesca - Nova Santa Rita, Berto Círio",
                            Uf = "RS"
                        },
                        new
                        {
                            IdLoja = 17,
                            NomeLoja = "Droga Raia - Novo Hamburgo, Boa Saúde",
                            Uf = "RS"
                        });
                });

            modelBuilder.Entity("click_collect.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente");

                    b.Property<int>("LojaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("loja");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdProduto");

                    b.HasIndex("ClienteId");

                    b.HasIndex("LojaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            IdProduto = 1,
                            ClienteId = 1,
                            LojaId = 1,
                            NomeProduto = "Big Mac"
                        },
                        new
                        {
                            IdProduto = 2,
                            ClienteId = 2,
                            LojaId = 1,
                            NomeProduto = "McChicken"
                        },
                        new
                        {
                            IdProduto = 3,
                            ClienteId = 3,
                            LojaId = 1,
                            NomeProduto = "Batata Frita Grande"
                        },
                        new
                        {
                            IdProduto = 4,
                            ClienteId = 4,
                            LojaId = 1,
                            NomeProduto = "Refrigerante 500ml"
                        },
                        new
                        {
                            IdProduto = 5,
                            ClienteId = 5,
                            LojaId = 1,
                            NomeProduto = "McFlurry Ovomaltine"
                        },
                        new
                        {
                            IdProduto = 6,
                            ClienteId = 6,
                            LojaId = 2,
                            NomeProduto = "Camiseta Básica Branca"
                        },
                        new
                        {
                            IdProduto = 7,
                            ClienteId = 7,
                            LojaId = 2,
                            NomeProduto = "Calça Jeans Skinny"
                        },
                        new
                        {
                            IdProduto = 8,
                            ClienteId = 8,
                            LojaId = 2,
                            NomeProduto = "Jaqueta de Couro"
                        },
                        new
                        {
                            IdProduto = 9,
                            ClienteId = 9,
                            LojaId = 2,
                            NomeProduto = "Tênis Casual Preto"
                        },
                        new
                        {
                            IdProduto = 10,
                            ClienteId = 10,
                            LojaId = 2,
                            NomeProduto = "Vestido Floral"
                        },
                        new
                        {
                            IdProduto = 11,
                            ClienteId = 11,
                            LojaId = 3,
                            NomeProduto = "Internet 500 Mega"
                        },
                        new
                        {
                            IdProduto = 12,
                            ClienteId = 12,
                            LojaId = 3,
                            NomeProduto = "Combo TV + Internet"
                        },
                        new
                        {
                            IdProduto = 13,
                            ClienteId = 13,
                            LojaId = 3,
                            NomeProduto = "Ponto Adicional TV"
                        },
                        new
                        {
                            IdProduto = 14,
                            ClienteId = 14,
                            LojaId = 3,
                            NomeProduto = "Roteador Wi-Fi Mesh"
                        },
                        new
                        {
                            IdProduto = 15,
                            ClienteId = 15,
                            LojaId = 3,
                            NomeProduto = "Plano Fixo Ilimitado"
                        },
                        new
                        {
                            IdProduto = 16,
                            ClienteId = 16,
                            LojaId = 4,
                            NomeProduto = "Frappuccino Morango"
                        },
                        new
                        {
                            IdProduto = 17,
                            ClienteId = 17,
                            LojaId = 4,
                            NomeProduto = "Cappuccino Tradicional"
                        },
                        new
                        {
                            IdProduto = 18,
                            ClienteId = 18,
                            LojaId = 4,
                            NomeProduto = "Espresso Duplo"
                        },
                        new
                        {
                            IdProduto = 19,
                            ClienteId = 19,
                            LojaId = 4,
                            NomeProduto = "Pão de Queijo"
                        },
                        new
                        {
                            IdProduto = 20,
                            ClienteId = 20,
                            LojaId = 4,
                            NomeProduto = "Muffin de Mirtilo"
                        },
                        new
                        {
                            IdProduto = 21,
                            ClienteId = 1,
                            LojaId = 5,
                            NomeProduto = "Trudel Doce de Leite"
                        },
                        new
                        {
                            IdProduto = 22,
                            ClienteId = 2,
                            LojaId = 5,
                            NomeProduto = "Trudel de Nutella"
                        },
                        new
                        {
                            IdProduto = 23,
                            ClienteId = 3,
                            LojaId = 5,
                            NomeProduto = "Trudel Tradicional"
                        },
                        new
                        {
                            IdProduto = 24,
                            ClienteId = 4,
                            LojaId = 5,
                            NomeProduto = "Trudel com Morango"
                        },
                        new
                        {
                            IdProduto = 25,
                            ClienteId = 5,
                            LojaId = 5,
                            NomeProduto = "Água Mineral Sem Gás"
                        },
                        new
                        {
                            IdProduto = 26,
                            ClienteId = 6,
                            LojaId = 6,
                            NomeProduto = "Kalzone de Frango"
                        },
                        new
                        {
                            IdProduto = 27,
                            ClienteId = 7,
                            LojaId = 6,
                            NomeProduto = "Kalzone de Calabresa"
                        },
                        new
                        {
                            IdProduto = 28,
                            ClienteId = 8,
                            LojaId = 6,
                            NomeProduto = "Kalzone 4 Queijos"
                        },
                        new
                        {
                            IdProduto = 29,
                            ClienteId = 9,
                            LojaId = 6,
                            NomeProduto = "Suco Natural Laranja"
                        },
                        new
                        {
                            IdProduto = 30,
                            ClienteId = 10,
                            LojaId = 6,
                            NomeProduto = "Kalzone de Chocolate"
                        },
                        new
                        {
                            IdProduto = 31,
                            ClienteId = 11,
                            LojaId = 7,
                            NomeProduto = "Xis Salada"
                        },
                        new
                        {
                            IdProduto = 32,
                            ClienteId = 12,
                            LojaId = 7,
                            NomeProduto = "Cachorro Quente Duplo"
                        },
                        new
                        {
                            IdProduto = 33,
                            ClienteId = 13,
                            LojaId = 7,
                            NomeProduto = "Pastel de Carne"
                        },
                        new
                        {
                            IdProduto = 34,
                            ClienteId = 14,
                            LojaId = 7,
                            NomeProduto = "Refrigerante Lata 350ml"
                        },
                        new
                        {
                            IdProduto = 35,
                            ClienteId = 15,
                            LojaId = 7,
                            NomeProduto = "Porção de Fritas"
                        },
                        new
                        {
                            IdProduto = 36,
                            ClienteId = 16,
                            LojaId = 8,
                            NomeProduto = "Sorvete Chocolate 2L"
                        },
                        new
                        {
                            IdProduto = 37,
                            ClienteId = 17,
                            LojaId = 8,
                            NomeProduto = "Picolé de Uva"
                        },
                        new
                        {
                            IdProduto = 38,
                            ClienteId = 18,
                            LojaId = 8,
                            NomeProduto = "Sundae Caramelo"
                        },
                        new
                        {
                            IdProduto = 39,
                            ClienteId = 19,
                            LojaId = 8,
                            NomeProduto = "Milkshake Morango"
                        },
                        new
                        {
                            IdProduto = 40,
                            ClienteId = 20,
                            LojaId = 8,
                            NomeProduto = "Pote Flocos 1,5L"
                        },
                        new
                        {
                            IdProduto = 41,
                            ClienteId = 1,
                            LojaId = 9,
                            NomeProduto = "Frango Teriyaki 15cm"
                        },
                        new
                        {
                            IdProduto = 42,
                            ClienteId = 2,
                            LojaId = 9,
                            NomeProduto = "Baratíssimo de Frango"
                        },
                        new
                        {
                            IdProduto = 43,
                            ClienteId = 3,
                            LojaId = 9,
                            NomeProduto = "BMT 30cm"
                        },
                        new
                        {
                            IdProduto = 44,
                            ClienteId = 4,
                            LojaId = 9,
                            NomeProduto = "Cookie Gotas Chocolate"
                        },
                        new
                        {
                            IdProduto = 45,
                            ClienteId = 5,
                            LojaId = 9,
                            NomeProduto = "Refrigerante Refil"
                        },
                        new
                        {
                            IdProduto = 46,
                            ClienteId = 6,
                            LojaId = 10,
                            NomeProduto = "Tênis Air Max"
                        },
                        new
                        {
                            IdProduto = 47,
                            ClienteId = 7,
                            LojaId = 10,
                            NomeProduto = "Camiseta Dri-FIT"
                        },
                        new
                        {
                            IdProduto = 48,
                            ClienteId = 8,
                            LojaId = 10,
                            NomeProduto = "Calça de Moletom"
                        },
                        new
                        {
                            IdProduto = 49,
                            ClienteId = 9,
                            LojaId = 10,
                            NomeProduto = "Meias Esportivas Cano Alto"
                        },
                        new
                        {
                            IdProduto = 50,
                            ClienteId = 10,
                            LojaId = 10,
                            NomeProduto = "Bola de Futebol Campo"
                        },
                        new
                        {
                            IdProduto = 51,
                            ClienteId = 11,
                            LojaId = 11,
                            NomeProduto = "Tênis Ultraboost"
                        },
                        new
                        {
                            IdProduto = 52,
                            ClienteId = 12,
                            LojaId = 11,
                            NomeProduto = "Jaqueta Corta Vento"
                        },
                        new
                        {
                            IdProduto = 53,
                            ClienteId = 13,
                            LojaId = 11,
                            NomeProduto = "Mochila Esportiva"
                        },
                        new
                        {
                            IdProduto = 54,
                            ClienteId = 14,
                            LojaId = 11,
                            NomeProduto = "Shorts de Corrida"
                        },
                        new
                        {
                            IdProduto = 55,
                            ClienteId = 15,
                            LojaId = 11,
                            NomeProduto = "Boné Logo Adidas"
                        },
                        new
                        {
                            IdProduto = 56,
                            ClienteId = 16,
                            LojaId = 12,
                            NomeProduto = "Tênis 574 Casual"
                        },
                        new
                        {
                            IdProduto = 57,
                            ClienteId = 17,
                            LojaId = 12,
                            NomeProduto = "Tênis 1080 Corrida"
                        },
                        new
                        {
                            IdProduto = 58,
                            ClienteId = 18,
                            LojaId = 12,
                            NomeProduto = "Camiseta de Corrida"
                        },
                        new
                        {
                            IdProduto = 59,
                            ClienteId = 19,
                            LojaId = 12,
                            NomeProduto = "Top Esportivo Feminino"
                        },
                        new
                        {
                            IdProduto = 60,
                            ClienteId = 20,
                            LojaId = 12,
                            NomeProduto = "Viseira Ajustável"
                        },
                        new
                        {
                            IdProduto = 61,
                            ClienteId = 1,
                            LojaId = 13,
                            NomeProduto = "Dipirona 500mg"
                        },
                        new
                        {
                            IdProduto = 62,
                            ClienteId = 2,
                            LojaId = 13,
                            NomeProduto = "Shampoo Anticaspa Clear"
                        },
                        new
                        {
                            IdProduto = 63,
                            ClienteId = 3,
                            LojaId = 13,
                            NomeProduto = "Desodorante Rexona"
                        },
                        new
                        {
                            IdProduto = 64,
                            ClienteId = 4,
                            LojaId = 13,
                            NomeProduto = "Sabonete Líquido Dove"
                        },
                        new
                        {
                            IdProduto = 65,
                            ClienteId = 5,
                            LojaId = 13,
                            NomeProduto = "Fralda Pampers M"
                        },
                        new
                        {
                            IdProduto = 66,
                            ClienteId = 6,
                            LojaId = 14,
                            NomeProduto = "Vitamina C Efervescente"
                        },
                        new
                        {
                            IdProduto = 67,
                            ClienteId = 7,
                            LojaId = 14,
                            NomeProduto = "Protetor Solar FPS 50"
                        },
                        new
                        {
                            IdProduto = 68,
                            ClienteId = 8,
                            LojaId = 14,
                            NomeProduto = "Hidratante Corporal Corporal"
                        },
                        new
                        {
                            IdProduto = 69,
                            ClienteId = 9,
                            LojaId = 14,
                            NomeProduto = "Escova de Dentes Macia"
                        },
                        new
                        {
                            IdProduto = 70,
                            ClienteId = 10,
                            LojaId = 14,
                            NomeProduto = "Absorvente Noturno"
                        },
                        new
                        {
                            IdProduto = 71,
                            ClienteId = 11,
                            LojaId = 15,
                            NomeProduto = "Paracetamol 750mg"
                        },
                        new
                        {
                            IdProduto = 72,
                            ClienteId = 12,
                            LojaId = 15,
                            NomeProduto = "Creme Dental Colgate"
                        },
                        new
                        {
                            IdProduto = 73,
                            ClienteId = 13,
                            LojaId = 15,
                            NomeProduto = "Álcool em Gel 70%"
                        },
                        new
                        {
                            IdProduto = 74,
                            ClienteId = 14,
                            LojaId = 15,
                            NomeProduto = "Curativos Band-Aid"
                        },
                        new
                        {
                            IdProduto = 75,
                            ClienteId = 15,
                            LojaId = 15,
                            NomeProduto = "Soro Fisiológico 500ml"
                        },
                        new
                        {
                            IdProduto = 76,
                            ClienteId = 16,
                            LojaId = 16,
                            NomeProduto = "Vara de Pesca Carbono"
                        },
                        new
                        {
                            IdProduto = 77,
                            ClienteId = 17,
                            LojaId = 16,
                            NomeProduto = "Isca Artificial Sapinho"
                        },
                        new
                        {
                            IdProduto = 78,
                            ClienteId = 18,
                            LojaId = 16,
                            NomeProduto = "Barraca Camping 4 Pessoas"
                        },
                        new
                        {
                            IdProduto = 79,
                            ClienteId = 19,
                            LojaId = 16,
                            NomeProduto = "Canivete Suíço 12 Funções"
                        },
                        new
                        {
                            IdProduto = 80,
                            ClienteId = 20,
                            LojaId = 16,
                            NomeProduto = "Lanterna de Cabeça LED"
                        },
                        new
                        {
                            IdProduto = 81,
                            ClienteId = 1,
                            LojaId = 17,
                            NomeProduto = "Ração Golden Cães 15kg"
                        },
                        new
                        {
                            IdProduto = 82,
                            ClienteId = 2,
                            LojaId = 17,
                            NomeProduto = "Coleira Anti-pulgas"
                        },
                        new
                        {
                            IdProduto = 83,
                            ClienteId = 3,
                            LojaId = 17,
                            NomeProduto = "Brinquedo Osso Borracha"
                        },
                        new
                        {
                            IdProduto = 84,
                            ClienteId = 4,
                            LojaId = 17,
                            NomeProduto = "Petisco Bifinho Sabor Carne"
                        },
                        new
                        {
                            IdProduto = 85,
                            ClienteId = 5,
                            LojaId = 17,
                            NomeProduto = "Areia Higiênica Gatos 4kg"
                        });
                });

            modelBuilder.Entity("click_collect.Produto", b =>
                {
                    b.HasOne("click_collect.Cliente", "Cliente")
                        .WithMany("Produtos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("click_collect.Loja", "Loja")
                        .WithMany("Produtos")
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Loja");
                });

            modelBuilder.Entity("click_collect.Cliente", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("click_collect.Loja", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
